export const CREATE_EDUCATION_REQUEST = "CREATE_EDUCATION_REQUEST";
export const CREATE_EDUCATION_SUCCESS = "CREATE_EDUCATION_SUCCESS";
export const CREATE_EDUCATION_FAILURE = "CREATE_EDUCATION_FAILURE";

export const GET_EDUCATION_REQUEST = "GET_EDUCATION_REQUEST";
export const GET_EDUCATION_SUCCESS = "GET_EDUCATION_SUCCESS";
export const GET_EDUCATION_FAILURE = "GET_EDUCATION_FAILURE";

export const GET_EDUCATION_BYID_REQUEST = "GET_EDUCATION_BYID_REQUEST";
export const GET_EDUCATION_BYID_SUCCESS = "GET_EDUCATION_BYID_SUCCESS";
export const GET_EDUCATION_BYID_FAILURE = "GET_EDUCATION_BYID_FAILURE";

export const UPDATE_EDUCATION_BYID_REQUEST = "UPDATE_EDUCATION_BYID_REQUEST";
export const UPDATE_EDUCATION_BYID_SUCCESS = "UPDATE_EDUCATION_BYID_SUCCESS";
export const UPDATE_EDUCATION_BYID_FAILURE = "UPDATE_EDUCATION_BYID_FAILURE";

export const DELETE_EDUCATION_BYID_REQUEST = "DELETE_EDUCATION_BYID_REQUEST";
export const DELETE_EDUCATION_BYID_SUCCESS = "DELETE_EDUCATION_BYID_SUCCESS";
export const DELETE_EDUCATION_BYID_FAILURE = "DELETE_EDUCATION_BYID_FAILURE";